######################## default configuration ####################
baseURL = "https://zabel.biz"
title = "Lennox Zabel"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "fonts/rubik.css"
#[[params.plugins.css]]
#link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Kontakt"
URL = "mailto:zabel@mf.me"
weight = 1

[[menu.main]]
name = "Impressum"
URL = "impressum.pdf"
weight = 2

[[menu.main]]
name = "Datenschutz"
URL = "datenschutz.pdf"
weight = 3

#################### default parameters ################################
[params]
copyright = "Copyright Lennox Zabel &copy;"
# Meta data
description = "Lennox Zabel"
author = "Lennox Zabel"
favicon = "images/icon.png"
logo_light = "images/logo-white.png"
logo_dark = "images/logo-dark.png"

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################
[caches]
  [caches.images]
    dir = ':cacheDir/images'
